apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
    worker_connections  1024;
     }


    http {
    #include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;
    proxy_http_version 1.1;
    #gzip  on;

    include /etc/nginx/conf.d/*.conf;

       server {
    listen 80;
    server_name zone1;

    location = /app1 {
      proxy_pass http://zone2/app1;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone1";
             }
  
    location = /app2 {
      proxy_pass http://zone2/app2;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone1";
            } 

    location = /app3 {
      proxy_pass http://zone3/app3;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone1";
            }


    location /app4 {
      proxy_pass http://zone3/app4;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone1";
            }
    
        }

    server {
    listen 80;
    server_name zone2;

    location = /app1 {
      proxy_pass http://zone4/app1;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone2";
            }

    location = /app2 {
      proxy_pass http://zone5/app2;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone2";
            }
    
        }

    server {
    listen 80;
    server_name zone3;

    location = /app3 {
      proxy_pass http://zone5/app3;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone3";
            }

    location = /app4 {
      proxy_pass http://zone4/app4;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone3";
            } 
         }

    server {
    listen 80;
    server_name zone4;

    location = /app1 {
      proxy_pass http://zone6/app1;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone4";
            }

    location = /app4 {
      proxy_pass http://zone6/app4;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone4";
            } 
         }

    server {
    listen 80;
    server_name zone5;

    location = /app2 {
      proxy_pass http://zone7/app2;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone5";
            }

    location = /app3 {
      proxy_pass http://zone7/app3;
      proxy_set_header     X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Cookie "$http_cookie, loc=zone5";
            } 
         }


    }
  
